version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      # SSH設定
      - ${HOME}/.ssh:/tmp/.ssh:ro
      # GitHub CLI設定
      - ${HOME}/.config/gh:/home/vscode/.config/gh:ro
      # Claude設定
      - ${HOME}/.claude:/home/vscode/.claude:ro
      - ${HOME}/.claude.json:/home/vscode/.claude.json:ro
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=router_manager
      - DB_SSLMODE=disable
    depends_on:
      postgres:
        condition: service_healthy
    command: sleep infinity

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=router_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../db/schema/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
