root = "."
tmp_dir = "/tmp/route-manager-go-batch"

[build]
bin = "/tmp/route-manager-go-batch/main"
cmd = "go build -o /tmp/route-manager-go-batch/main ./cmd/batch/"
full_bin = "ENV=local /tmp/route-manager-go-batch/main"
delay = 1000
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test.go"]
include_ext = ["go"]
