root = "."
tmp_dir = "/tmp/router-manager-api"

[build]
bin = "/tmp/router-manager-api/main"
cmd = "go build -o /tmp/router-manager-api/main ./cmd/api/"
full_bin = "ENV=local /tmp/router-manager-api/main"
delay = 1000
exclude_dir = ["tmp", "vendor"]
exclude_regex = ["_test.go"]
include_ext = ["go"]
